# Generated by Django 4.0.1 on 2022-12-19 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_boardparticipant_board_and_more'),
    ]

    operations = [
    ]
